[tool.poetry]
name = "mlops_exo"
version = "0.1.0"
description = "mlops exercices"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.2.1"
pandas = "^2.2.3"
ruff = "^0.8.4"
pytest = "^8.3.4"
mlflow = "^2.19.0"
openpyxl = "^3.1.5"
scikit-learn = "^1.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
