name: CI/CD for Machine Learning Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Vérifiez le dépôt du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Vous pouvez ajuster la version selon vos besoins

      # Étape 3 : installer poetry
      - name: Install Poetry
        run: |
      #     TODO : écrire instruction pour installer poetry

      # Étape 4 : TODO : installer les dépendances avec poetry
      # ------------------------------------------------------------------------------------
      #
      #
      #
      #
      # ------------------------------------------------------------------------------------

      # Étape 5 : TODO : appliquer le linter ruff
      # ------------------------------------------------------------------------------------
      #
      #
      #
      #
      # ------------------------------------------------------------------------------------


      # Étape 6 : TODO Lancer les tests unitaires
      # ------------------------------------------------------------------------------------
      #
      #
      #
      #
      # ------------------------------------------------------------------------------------
